name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on Linux
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.21.3

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_ALL_LINUX: yum install -y libicu-devel sqlite-devel
          CIBW_SKIP: "*-musllinux_*"

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
